const mongoose = require("mongoose");

const RoadmapSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    topic: {
      type: String,
      required: true,
      trim: true,
    },
    roadmapData: {
      type: String, // Stores the rich Markdown text string generated by Gemini
      required: true,
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model("Roadmap", RoadmapSchema);